name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - automated_builds

jobs:
  release:
    name: Publish on GitHub
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: "x86_64-unknown-linux-gnu" }
          - { os: macos-latest, target: "x86_64-apple-darwin" }
          - { os: windows-latest, target: "x86_64-pc-windows-msvc" }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install \
            --allow-unauthenticated -y -qq \
              libgtk-3-dev \
              webkit2gtk-4.0 \
              libappindicator3-dev \
              librsvg2-dev patchelf

      - name: Install node
        uses: actions/setup-node@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
          override: true
          profile: minimal

      - name: Build CLI
        working-directory: cli
        shell: bash
        run: |
          cargo build --verbose --locked \
            --release --target ${{ matrix.config.target }}

      - name: Build GUI
        working-directory: gui
        shell: bash
        run: |
          yarn install --ignore-engines
          yarn tauri info
          yarn tauri build --target ${{ matrix.config.target }}
